apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p32nfxqqb-python 
  janus-idp.io/tekton: p32nfxqqb-python
  backstage.io/kubernetes-id: p32nfxqqb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p32nfxqqb-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  